### ISSUE TITLE
mobile_yaml Application: Changing Background Map Error

### ISSUE THREAD

**Issue by RobinSchwammborn** [mapbender/mapbender-starter#45]
A error message pops up when the background map is changed in the mobile application. Take a look at this screenshot.

### OSM_Background_Changing:
![change_background](https://cloud.githubusercontent.com/assets/21199730/25175785/4c08b53c-24fc-11e7-9d9d-367198aca10b.png)

**Comment by eSlider** [comment]
There is a lot of bugs:
* [x] Application copying files by import. Recursive. Fixed.
* [x] Displaying source ID error message. Fixed.
* [x] Component code directly in import command code. Fixed and Refactored.
* [ ] Base source switcher detecting layer sources. Open.

I still working on...

**Comment by RobinSchwammborn** [comment]
Maybe a little hint regarding the switcher project - I'm not quite sure if it solves the problem: In my case, the default OSM instances weren't set in the background switcher element. I selected them (orange colour) and the error didn't occur anymore...Screenshot:

![mobile_app_backgroundswitcher_shouldbedefault](https://cloud.githubusercontent.com/assets/21199730/25396034/61331542-29e3-11e7-8ca9-6668651d4eeb.png)
